# Generated by Django 5.2.1 on 2025-05-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='difficulty',
            options={'verbose_name_plural': 'Difficulties'},
        ),
        migrations.AddField(
            model_name='task',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
