# Generated by Django 5.2.1 on 2025-05-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_category_options_alter_difficulty_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
    ]
